
class TextConstants {

  static String titleTab_1 = "Home";
  static String titleTab_2 = "Device Finder";
  static String titleTab_3 = "About Me";
}

const Map<String, String> bleUuidNames = {

  // Services
  "1800": "Generic Access",
  "1801": "Generic Attribute",
  "1802": "Immediate Alert",
  "1803": "Link Loss",
  "1804": "Tx Power",
  "1805": "Current Time Service",
  "1806": "Reference Time Update Service",
  "1807": "Next DST Change Service",
  "1808": "Glucose",
  "1809": "Health Thermometer",
  "180A": "Device Information",
  "180D": "Heart Rate",
  "180E": "Phone Alert Status Service",
  "180F": "Battery Service",
  "1810": "Blood Pressure",
  "1811": "Alert Notification Service",
  "1812": "Human Interface Device",
  "1813": "Scan Parameters",
  "1814": "Running Speed and Cadence",
  "1815": "Automation IO",
  "1816": "Cycling Speed and Cadence",
  "1818": "Cycling Power",
  "1819": "Location and Navigation",
  "181A": "Environmental Sensing",
  "181B": "Body Composition",
  "181C": "User Data",
  "181D": "Weight Scale",
  "181E": "Bond Management",
  "181F": "Continuous Glucose Monitoring",
  "1820": "Internet Protocol Support",
  "1821": "Indoor Positioning",
  "1822": "Pulse Oximeter",
  "1823": "HTTP Proxy",
  "1824": "Transport Discovery",
  "1825": "Object Transfer",
  "1826": "Fitness Machine",
  "1827": "Mesh Provisioning",
  "1828": "Mesh Proxy",
  "1829": "Reconnection Configuration",
  "183A": "Insulin Delivery",

  // Characteristics
  "2A00": "Device Name",
  "2A01": "Appearance",
  "2A02": "Peripheral Privacy Flag",
  "2A03": "Reconnection Address",
  "2A04": "Peripheral Preferred Connection Parameters",
  "2A05": "Service Changed",
  "2A06": "Alert Level",
  "2A07": "Tx Power Level",
  "2A08": "Date Time",
  "2A09": "Day of Week",
  "2A0A": "Day Date Time",
  "2A0C": "Exact Time 256",
  "2A0D": "DST Offset",
  "2A0E": "Time Zone",
  "2A10": "Local Time Information",
  "2A12": "Intermediate Temperature",
  "2A13": "Measurement Interval",
  "2A14": "Boot Keyboard Input Report",
  "2A16": "Boot Keyboard Output Report",
  "2A17": "Boot Mouse Input Report",
  "2A18": "Glucose Measurement",
  "2A19": "Battery Level",
  "2A1A": "Battery Power State",
  "2A1B": "Battery Level State",
  "2A1C": "Temperature Measurement",
  "2A1D": "Temperature Type",
  "2A1E": "Intermediate Cuff Pressure",
  "2A21": "Measurement Interval",
  "2A22": "Boot Keyboard Input Report",
  "2A23": "System ID",
  "2A24": "Model Number String",
  "2A25": "Serial Number String",
  "2A26": "Firmware Revision String",
  "2A27": "Hardware Revision String",
  "2A28": "Software Revision String",
  "2A29": "Manufacturer Name String",
  "2A2A": "IEEE 11073-20601 Regulatory Certification Data List",
  "2A2B": "Current Time",
  "2A2C": "Magnetic Declination",
  "2A31": "Heart Rate Sensor Location",
  "2A32": "Heart Rate Measurement",
  "2A33": "Boot Keyboard Output Report",
  "2A34": "Glucose Feature",
  "2A35": "Blood Pressure Measurement",
  "2A36": "Intermediate Cuff Pressure",
  "2A37": "Heart Rate Measurement",
  "2A38": "Body Sensor Location",
  "2A39": "Heart Rate Control Point",
  "2A3F": "Alert Status",
  "2A49": "Number of Digitals",
  "2A4A": "Position Quality",
  "2A4B": "LN Feature",
  "2A4C": "LN Control Point",
  "2A4D": "Elevation",
  "2A4E": "Pressure",
  "2A4F": "Temperature",
  "2A50": "PnP ID",
  "2A51": "Glucose Measurement Context",
  "2A52": "Record Access Control Point",
  "2A53": "RSC Measurement",
  "2A54": "RSC Feature",
  "2A55": "SC Control Point",
  "2A5A": "Aggregate",
  "2A5B": "CSC Measurement",
  "2A5C": "CSC Feature",
  "2A5D": "Sensor Location",
  "2A60": "Cycling Power Measurement",
  "2A61": "Cycling Power Vector",
  "2A62": "Cycling Power Feature",
  "2A63": "Cycling Power Control Point",
  "2A64": "Location and Speed",
  "2A65": "Navigation",
  "2A66": "Position Quality",
  "2A67": "LN Feature",
  "2A68": "NDS Control Point",
  "2A69": "Static Navigation",
  "2A6A": "Pollen Concentration",
  "2A6B": "Weather Station Data",
  "2A6C": "Wind Speed",
  "2A6D": "Humidity",
  "2A6E": "True Wind Direction",
  "2A6F": "Temperature",
  "2A70": "Temperature Measurement",
  "2A71": "Temperature Type",
  "2A72": "Time Zone",
  "2A73": "Time with DST",
  "2A74": "Time Accuracy",
  "2A75": "Time Source",
  "2A76": "Reference Time Information",
  "2A77": "Time Update Control Point",
  "2A78": "Time Update State",
  "2A79": "Glucose Feature",
  "2A7A": "Battery Level State",
  "2A7B": "Battery Power State",
  "2A7D": "Central Address Resolution",
  "2A7E": "CGM Measurement",
  "2A7F": "CGM Feature",
  "2A80": "CGM Status",
  "2A81": "CGM Session Start Time",
  "2A82": "CGM Session Run Time",
  "2A83": "CGM Specific Ops Control Point",
  "2A84": "Indoor Positioning Configuration",
  "2A85": "Latitude",
  "2A86": "Longitude",
  "2A87": "Local North Coordinate",
  "2A88": "Local East Coordinate",
  "2A89": "Floor Number",
  "2A8A": "Altitude",
  "2A8B": "Uncertainty",
  "2A8C": "Location Name",
  "2A8D": "URI",
  "2A8E": "HTTP Headers",
  "2A8F": "HTTP Status Code",
  "2A90": "HTTP Entity Body",
  "2A91": "HTTP Control Point",
  "2A92": "HTTPS Security",
  "2A93": "TDS Control Point",
  "2A94": "OTS Feature",
  "2A95": "Object Name",
  "2A96": "Object Type",
  "2A97": "Object Size",
  "2A98": "Object First-Created",
  "2A99": "Object Last-Modified",
  "2A9A": "Object ID",
  "2A9B": "Object Properties",
  "2A9C": "Object Action Control Point",
  "2A9D": "Object List Control Point",
  "2A9E": "Object List Filter",
  "2A9F": "Object Changed",
  "2AA0": "Resolvable Private Address Only",
  "2AA1": "Resolvable Private Address",
  "2AA2": "Device Time",
  "2AA3": "Device Time Feature",
  "2AA4": "Time Broadcast",
  "2AA5": "Gap Le Device Name",
  "2AA6": "Gap Appearance",
  "2AA7": "Gap Peripheral Privacy Flag",
  "2AA8": "Gap Reconnection Address",
  "2AA9": "Gap Peripheral Preferred Connection Parameters",
  "2AAA": "Gap Service Changed",
  "2AAB": "Gap Alert Level",
  "2AAC": "Gap Tx Power Level",
  "2AAD": "Gap Date Time",
  "2AAE": "Gap Day of Week",
  "2AAF": "Gap Day Date Time",
  "2AB0": "Gap Exact Time 256",
  "2AB1": "Gap DST Offset",
  "2AB2": "Gap Time Zone",
  "2AB3": "Gap Local Time Information",
  "2AB4": "Gap Secondary Time Zone",
  "2AB5": "Gap Time with DST",
  "2AB6": "Gap Time Accuracy",
  "2AB7": "Gap Time Source",
  "2AB8": "Gap Reference Time Information",

  // Additional Characteristics
  "2B29": "Media Control Point",
  "2B2A": "Media Control Point Opcodes",
  "2B2B": "Media Player Name",
  "2B2C": "Media Player Icon Object ID",
  "2B2D": "Media Player Icon URL",
  "2B2E": "Track Changed",
  "2B2F": "Track Title",
  "2B30": "Track Duration",
  "2B31": "Track Position",
  "2B32": "Playback Speed",
  "2B33": "Seeking Speed",
  "2B34": "Current Track Segments Object ID",
  "2B35": "Current Track Object ID",
  "2B36": "Next Track Object ID",
  "2B37": "Parent Group Object ID",
  "2B38": "Current Group Object ID",
  "2B39": "Playing Order",
  "2B3A": "Playing Orders Supported",
  "2B3B": "Media State",
  "2B3C": "Media Control Point Opcodes Supported",
  "2B3D": "Search Results Object ID",
  "2B3E": "Search Control Point",
  "2B3F": "Media Player Icon Object Type",
  "2B40": "Track Segments Object Type",
  "2B41": "Track Object Type",
  "2B42": "Group Object Type",
  "2B43": "Search Results Object Type",
  "2B44": "Content Control ID",
  "2B45": "Status",
  "2B46": "Control Point",
  "2B47": "Control Point Settings",
  "2B48": "Status Reader Control Point",
  "2B49": "Status Reader Result",
  "2B4A": "Active Preset Index",
  "2B4B": "Concentration",
  "2B4C": "Activity",
  "2B4D": "Sensor Status",
  "2B4E": "Fixed String",
};